resolver: lts-11.19
apply-ghc-options: everything
ghc-options: 
    '$everything': -Wall -opta-Wa,-mrelax-relocations=no
allow-newer: true
extra-deps:
- cubicbezier-0.6.0.5
- diagrams-1.4
- diagrams-cairo-1.4
- diagrams-contrib-1.4.2.1
- diagrams-core-1.4.0.1
- diagrams-lib-1.4.2
- diagrams-solve-0.1.1
- diagrams-svg-1.4.1.1
- dual-tree-0.2.1
- fast-math-1.0.2
- foldl-1.4.2
- Frames-0.4.0
- hvega-0.1.0.0
- ihaskell-0.9.1.0
- ihaskell-aeson-0.3.0.1
- ihaskell-blaze-0.3.0.1
- ihaskell-charts-0.3.0.1
- ihaskell-diagrams-0.3.2.1
- ihaskell-gnuplot-0.1.0.1
- ihaskell-hatex-0.2.1.1
- ihaskell-inline-r-0.1.1.0
- ihaskell-juicypixels-1.1.0.1
- ihaskell-magic-0.3.0.1
- ihaskell-plot-0.3.0.1
- ihaskell-widgets-0.2.3.2
- inline-r-0.9.2
- ipython-kernel-0.9.1.0
- magic-1.1
- mfsolve-0.3.2.0
- static-canvas-0.2.0.3
- vinyl-0.8.1
